## QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 815293528@qq.com
    password: bpylsfmfvvthbdjb #注意此密码不是邮箱登陆密码，而是邮箱的授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
register:
  config:
    limited-time-millis: 600000
    limit-number: 10
